<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)'==''">Release</Configuration>
    <OutputType>WinExe</OutputType>
    <AssemblyName>PokaAntiAFK</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <LangVersion>8.0</LangVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <ApplicationManifest>src\app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\poka.ico</ApplicationIcon>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Core" />
    <Reference Include="System.Drawing" /><Reference Include="System.Windows.Forms" />
    <Compile Include="src\*.cs" />
    <EmbeddedResource Include="assets\poka.ico"><LogicalName>PokaAntiAFK.AppIcon</LogicalName></EmbeddedResource>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
